name: Docs

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-09-23
          target: wasm32-unknown-unknown
          override: true
          components: rust-docs

      - name: Build website
        run: |
          cd docs
          yarn install
          yarn run build

      - name: Build rustdocs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps
